Updating docs
aimclub/ECG pull request #45
Opened 2023-07-31 18:55 UTC by jiGApache

Done:
- provided new api method description
- provided the result of testing of the new method

2023-08-05 12:54 UTC, tanyapole requested changes

2023-08-05 12:54 UTC, tanyapole commented on benchmarks_ptb_xl.md
> +All methods except of `ecg_is_normal` were trained on [CPSC 2018](http://2018.icbeb.org/Challenge.html). For benchmarking [PTB-XL](https://physionet.org/content/ptb-xl/1.0.1/) dataset was used.
except for

2023-08-05 12:54 UTC, tanyapole commented on benchmarks_ptb_xl.md
> +Method `ecg_is_normal` was trained, validated and tested on [PTB-XL](https://physionet.org/content/ptb-xl/1.0.1/) dataset. 1-8 folds were used for the training set, 9 fold for the validation set and
Folds 1-8 were used as the training set, fold 9 as the validation set and fold 10 as the test set

2023-08-05 12:54 UTC, tanyapole commented on benchmarks_ptb_xl.md
> +### ECG embedding classification
Название секции должно быть по рассматриваемому функционалу (выполняемой задаче), а не по методу решения. Т.е. вот эту строку убрать. А 41ю переделать из #### в ###

2023-08-05 12:54 UTC, tanyapole commented on benchmarks_ptb_xl.md
> +The following parameters were used to train the KNN-classifier:
Гиперпараметры модели лучше в methods.md отправить.

2023-08-05 12:54 UTC, tanyapole commented on methods.md
> +ECG classification is performed between normal and abnormal classes. The embeddings which are extracted with help of deep convolutional network are classified by k-nearest-neighbour classifier.
Добавьте пожалуйста описание, как строилась нейронка, с помощью которой извлекались эмбеддинги (была взята какая-то модель предобученная на ImageNet, или это нейронка обученная на целевом датасете. если на целевом - то на какой задаче (multiclass classification заболеваний, или какой-то SSL, или еще что-то).
Здесь уместно указать гиперпараметры KNN (если не сложно, распишите как вы их выбрали. Если сложно - забейте).

2023-08-05 12:54 UTC, tanyapole commented on methods.md
> +The KNN classifier is trained on a few shot data, as the greatest improvement in metric performance is observed on a small set of training data.
В каком смысле KNN обучался на few shot data? Из этой фразы не понятно, какие именно данные брались для обучения.

2023-08-09 23:09 UTC, MedAI-Lab-ITMO approved these changes

2023-08-09 23:10 UTC, tanyapole approved these changes

2023-08-09 23:10 UTC, merged